<?php
return [


    "Globe Gcash" => "Globe Gcash",
    'Robinsons' => 'Robinsons Bank',

    'ALLBANK (A Thrift Bank), Inc.' => 'ALLBANK (A Thrift Bank), Inc.',
    'AUB' => 'Asia United Bank',
    'Allbank Corp.' => 'Allbank Corp.',
    'Allied Banking Corp' => 'Allied Banking Corp',
//    'BDO Network Bank' => 'BDO Network Bank',
//    'BDO Network Bank, Inc.' => 'BDO Network Bank, Inc.',
    'BOC' => 'Bank Of Commerce',
    'BPI' => 'Bank Of The Philippine Islands',
//    'BPI Direct Banko, Inc., A Savings Bank' => 'BPI Direct Banko, Inc., A Savings Bank',
    'Banco De Oro Unibank, Inc.' => 'Banco De Oro Unibank, Inc.',
    'Bangko Mabuhay (A Rural Bank), Inc.' => 'Bangko Mabuhay (A Rural Bank), Inc.',
    'Binangonan Rural Bank Inc' => 'Bangko Mabuhay (A Rural Bank), Inc.',
    "CBC" => "Chinatrust Banking Corp",
//    "CBS" => "Chinabank Savings",
    "CSB" => "Citystate Savings Bank Inc.",
    "CTBC" => "CTBC Bank (Philippines) =>  Inc.",
    "Camalig" => "Camalig Bank",
    "Cebuana Lhuillier Rural Bank, Inc." => "Cebuana Lhuillier Rural Bank, Inc.",
    "Chinabank" => "Chinabank",
    "DBI" => "Dungganun Bank Inc.",
    "DCPay" => "DCPay Philippines Inc.",
    "EB" => "Eastwest Bank",
    "ERB" => "EastWest Rural Bank",
    "ESB" => "Equicom Savings Bank",

    "GrabPay" => "GrabPay Philippines",
    "ING" => "ING Bank N.V.",
    "ISLA Bank (A Thrift Bank) Inc." => "ISLA Bank (A Thrift Bank) Inc.",
    "Landbank of the Philippines" => "Landbank of the Philippines",
    "MB" => "Malayan Bank",
    "Maybank Philippines Inc." => "Maybank Philippines Inc.",
    "Metropolitan Bank and Trust Co" => "Metropolitan Bank and Trust Co",
    "Omnipay" => "Omnipay",
    "PB" => "Producers Bank",
    "PBB" => "Philippine Business Bank",
    "PBC" => "Philippine Bank of Communications",
    "PNB" => "Philippine National Bank",
    "PSB" => "Philippine Savings Bank",
    "PTC" => "Philippine Trust Company",
    "PVB" => "Philippine Veterans Bank",
    "Queen City Development Bank, Inc." => "Queen City Development Bank, Inc.",
    "Paymaya Philippines, Inc." => "Paymaya Philippines, Inc.",
    "RB" => "Robinsons Bank",
    "RBG" => "Rural Bank of Guinobatan Inc.",
    "Rizal Commercial Banking Corporation" => "Rizal Commercial Banking Corporation",
    "SBA" => "Sterling Bank Of Asia",
    "SBC" => "Security Bank Corporation",
    "SSB" => "Sun Savings Bank",
    "Starpay" => "Starpay",
    "UCPB SAVINGS BANK" => "UCPB SAVINGS BANK",
    "UnionBank" => "UnionBank",
//    "UnionBank EON" => "UnionBank EON",
    "United Coconut Planters Bank" => "United Coconut Planters Bank",
    "Wealth Development Bank, Inc." => "Wealth Development Bank,  Inc.",
    "Yuanta Savings Bank Inc." => "Yuanta Savings Bank Inc.",

    'CMB' => '招商银行',
    'ICBC' => '中国工商银行',
    'ABC' => '中国农业银行',
    'CCB' => '中国建设银行',
    'BOC' => '中国银行',
    'SPDB' => '浦发银行',
    'BCOM' => '中国交通银行',
    'CMBC' => '中国民生银行',
    'SDB' => '深圳发展银行',
    'GDB' => '广东发展银行',
    'CITIC' => '中信银行',
    'HXB' => '华夏银行',
    'CIB' => '兴业银行',
    'GZCB' => '广州银行',
    'UPOP' => '银联在线支付',
    'JSB' => '江苏银行',
    'SRCB' => '上海农村商业银行',
    'BOB' => '北京银行',
    'CBHB' => '渤海银行',
    'BJRCB' => '北京农商银行',
    'NJCB' => '南京银行',
    'CEB' => '中国光大银行',
    'BEA' => '东亚银行',
    'NBCB' => '宁波银行',
    'HZB' => '杭州银行',
    'PAB' => '平安银行',
    'HSB' => '徽商银行',
    'CZB' => '浙商银行',
    'SHB' => '上海银行',
    'PSBC' => '中国邮政储蓄银行',
    'DLB' => '大连银行',
    'ALIPAY' => '支付宝代付',
];

