<?php
return [
    'InnerChannel' => [
        'name' => '内部渠道',
        'open' => true,
        'openQuery' => false,
        'openPay' => false,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\InnerChannel",
        'paramDesc' => [
            'gateway' => '接口网关',
            'timeout' => '超时时间(秒)',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => '',
            'ipWhite' => '',
            'timeout' => 10,
        ],
    ],
    'mockTest' => [
        'name' => '测试上游支付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\MockTest",
        'paramDesc' => [
            'gateway' => '接口网关',
            'timeout' => '超时时间(秒)',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'http://mock.wldev01.com',
            'ipWhite' => '',
            'timeout' => 10,
        ],
    ],

    'wuxingzhifu' => [
        'name' => '五星代付',
        'open' => true,
        'openQuery' => true,
        'openPay' => false,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\Wuxingzhifu",
        'paramDesc' => [
            'gateway' => '接口网关',
            'apiKey' => '接口秘钥',
            'apiSerect' => '接口Secret',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://wuxingzhifu.com',
            'apiSerect' => 'bcfc93ef3d0b4f21861d876aafa0fa71',
            'apiKey' => 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ3NzIwMDAwMDEiLCJhdWRpZW5jZSI6IiIsImNyZWF0ZWQiOjE1NTQ3MDk5MTg3MTEsImlwIjoiNjAuMjUxLjUwLjQiLCJpZCI6IjY1NDA4ODUxIiwiZXhwIjoxODcwMDY5OTE4fQ.Kcf9Vbkkj2pEfoIg8hHAbISe3mXqLa11RAe2_pjTv9z8Jb7naVEPmwj6WyIvMyV-l1OWXBFauLyP1AnrE21KwA',
            'ipWhite' => '',
        ],
    ],

    'dsdfpay' => [
        'name' => '风云聚合',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => false,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\Dsdfpay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cid' => '商户号',
            'apiKey' => '接口秘钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://www.istmys.com',
            'cid' => 1294,
            'apiKey' => 'pqdEuEnX7pKLWI2M3l01Te2DjQ3TBLReS0bdIukZG5PCaM7Lf0X9s3c7DnX3ZWy7',
            'ipWhite' => '52.196.133.147, 13.115.67.208, 52.197.107.110',
        ],
    ],

    'uuxjw' => [
        'name' => '菠萝蜜',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => false,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\Uuxjw",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cid' => '商户号',
            'apiKey' => '接口秘钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://www.uuxjw.com',
            'cid' => 40249,
            'apiKey' => 'wLCjLq78D0cJwn2v0Zanyhlph66IJ476',
            'ipWhite' => '47.90.127.96, 13.125.165.60, 182.16.63.114',
        ],
    ],

    'lefutong' => [
        'name' => '乐付通',
        'open' => true,
        'openQuery' => true,
        'openPay' => false,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\Lefutong",
        'apiCharset' => 'gbk',
        'paramDesc' => [
            'gateway' => '接口网关',
            'organizationNo' => '机构号',
            'cNo' => '商户号',
            'apiKey' => '接口秘钥',
            'apiSettlementKey' => '接口结算秘钥',
            'virtualCardNo' => '虚拟卡号',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'http://zbdah.com',
            'organizationNo' => '6860110101',
            'cNo' => '686360853310001',
            'apiKey' => '3AC6D48582D2BD73DCDD9A7E49AE8E96',
            'apiSettlementKey' => '34E69EC081572A6EAB9403D34CC25158',
            'virtualCardNo' => '686011010100000168',
            'ipWhite' => '193.112.30.72',
        ],
    ],

    'nmpay' => [
        'name' => '糯米支付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\NmPay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cRemark' => '渠道备注',
            'cNo' => '商户号',
            'apiKey' => '接口秘钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'http://www.51vzsn.cn',
            'cRemark' => '糯米快捷',
            'cNo' => '4092201906017',
            'apiKey' => 'WDABRBTCOJXRKLJCUFMQHAHJLWYYAQBI',
            'ipWhite' => '47.52.108.72,47.75.204.4',
        ],
    ],

    'newmoney' => [
        'name' => '大唐支付',
        'open' => true,
        'openQuery' => false,
        'openPay' => true,
        'openSettlement' => false,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\Newmoney",
        'paramDesc' => [
            'gateway' => '接口网关',
            'organizationNo' => '商户号',
            'apiKey' => '接口秘钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'http://order.newmoney88.com:39802/',
            'organizationNo' => '1559461667614',
            'apiKey' => '625fcc3d8b1841f585b73104ba25342f',
            'ipWhite' => '193.112.30.72',
        ],
    ],

    'ktwopay' => [
        'name' => 'k2支付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => false,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\Ktwopay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cId' => '商户号',
            'apiKey' => '接口秘钥',
            'apiSecret' => '接口Secret',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://pay.888pay888.uk',
            'cId' => 'U0100013338',
            'apiKey' => '15597884787490h4ywbxn0edh',
            'apiSecret' => '1559788478749xs66bdp3eqew',
            'ipWhite' => '35.164.29.114, 159.138.86.177, 35.164.166.133',
        ],
    ],

    'alipay' => [
        'name' => '支付宝',
        'open' => true,
        'openQuery' => true,
        'openPay' => false,
        'openSettlement' => true,
        'settlementType' => ['alipay' => '支付宝代付'],
        'path' => "\App\Channels\Lib\Alipay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'appAccount' => '支付宝账号',
            'appId' => '商户号',
            'pid' => 'PID',
            'appPrivateKey' => '接口私钥',
            'appPublicKey' => '接口公钥',
            'aliPublicKey' => '阿里公钥',
            'alipayRootCert' => '阿里根证书（新）',
            'loginAccount' => '登录账号',
            'loginPassword' => '登录密码',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://openapi.alipay.com/gateway.do',
            'appAccount' => '',
            'appId' => '2019060965440807',
            'appPrivateKey' => 'MIIEowIBAAKCAQEA9vVC+B2ZUVUWuH/Ds0oovirZ8OU0MTxlD3TZtTwL0HIEjUMtwoFG9uMs7/bxMqK43sfGa9LAX8GiKABJjJjhTEIyP/ksZsJHlyM+Wkuj+5hrM0jKyrO5qu73WeetN1tadiX9k96q25obaJJVBdqqGhRmbgTUXdeVYnP567HzyMrFkGYjUjXpoCEquA71mowdDgEFpKIBWtXxHDOzhUIClPiPeUinCV1DmQgcvMd0tSSDHo+c6K0QJu8VqCzb9kCg+XeknzpOdtjFQ1ntpE7/XCY+nOVVIDTeZf+LQpScDVvOQIyUS04YD5yIW3yPVVL9gMRBoR1Xz8ogT4qB1It+8wIDAQABAoIBAHE0eKB4IQHxeVrV5oXXZtnVltYgm04+myz8qZe0kM3alk+TDfTtgfRGqyDNGD/X69rjxQdEMr8yafzgNNbodc6ZQaOluz7XrC2SEFEf/2mjsvBtW9iTjnbW2Dg0RWjszYj/XUBdgADuocXL3oGyfOs7ksC4Iglqe6YH9/adOl09/87IxI9mn+s4J+jNzfzmYNeSsHbO+bEKLq8NMyS44f7JOWrQhUPyAaZ2IjTRTUWUnigUr9Iq/zifrUzOOLKWhqkrT+KgfNU6TiXIj/FXhJIsD/gQSaE7zwwVbaiCD46FTIiVixmwp3JlVZrGC/55ZuqqKSOHKgCJea7UZ7nOVoECgYEA/aogJwIdRLXBd3JZrGw6egWXL85GWtlO4GWP/mB3UR7rWEHWOAmLSDMlFHrkWclEmQ3js90fGoVDCznCnd1NRD11VKS+fOYwTATZoAOr5jrzA+xSsRl2w03UbVMGCVYjvYpwYMy63dVy1mHzbe5Vo3yyLrXs5kfQQ47mXok1r5MCgYEA+TtUQYoQ2CohXXh7KcPZb6YzIKjXaThLtSHFhNP5fJSDhm5kv16EKwL45Hn2T8fY3F+xG/Y1wEpwdbHSyZGjKkpRE0XCMWYx3GpdAommpNCvO0Sjdu9mE80OhXRORSHDalLNEvdcDNmtSGBotWFr+0727SeNYcTkN1C8wo64zyECgYEAhUZaSER7Hjukn15sMQRYIP5I9ewZ2Oet4oZaBlumtO9a1W8Z3y1ciZ2dkMoUqfvuV8ANb9Xw3p0/oWlCkHDShNUJjWRVVQgYPgiaUtE7AubcAaart7LaTDjbMGlblZI1iwNukd1fHOhlwq+KF6sOQaxlbddV1ZPLn4M4FFlg5JMCgYBSXBm+wrpIRLvb4ImKxq6e56Qzobf1jGXwSGW2PDpQwd8o2GgwmTJB6GyJTAhqWtc+E906KUWf8rlxGz9V3uu1ePOL09yVaHkHpppv0T8hbdjKVCdUkU4BMx0eWs3WqI6kHxKntthTYseRiFJxxeziEjklK5HcAi2MXgDSpklKIQKBgGgn+glZb+cvlhZvRiNbAVS44nm/9n0tegy5DMhOtIyO7HLjsiLC6y3e0z/H3VMAqkKJdjMX+LN/KqBkdBjJMvAZDUyyeOMjueNM3Uzgo6Hv7EN+pG1gyD1YlDQnZ0SDtzBIWl+YJlmq8W/Eut+MOeUXrlZSTCHJRSTKav6dXC0U',
            'appPublicKey' => 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9vVC+B2ZUVUWuH/Ds0oovirZ8OU0MTxlD3TZtTwL0HIEjUMtwoFG9uMs7/bxMqK43sfGa9LAX8GiKABJjJjhTEIyP/ksZsJHlyM+Wkuj+5hrM0jKyrO5qu73WeetN1tadiX9k96q25obaJJVBdqqGhRmbgTUXdeVYnP567HzyMrFkGYjUjXpoCEquA71mowdDgEFpKIBWtXxHDOzhUIClPiPeUinCV1DmQgcvMd0tSSDHo+c6K0QJu8VqCzb9kCg+XeknzpOdtjFQ1ntpE7/XCY+nOVVIDTeZf+LQpScDVvOQIyUS04YD5yIW3yPVVL9gMRBoR1Xz8ogT4qB1It+8wIDAQAB',
            'aliPublicKey' => 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhnNMtOJ/ugVZXXmSgICG3E4kVTKL0ZKPqQMAoalkwbti/rfIG067VZUfuTkKk4M0Et1GuNxHdijLAWviuP7MpnoH8FUEhuHKrAIE5cWjLa8rwdzhaNxTTM+R0/DV21Pkz+j06Sq40GeVP/soRy2PtAoOeCzmIMpNQ63+Riw435GdqkORhcRPgps8QyYKMb8OVS3PkX32ya7Y573nMxR8xaIGJ88TcHgEPvsIW7jgalOX+2d6EEJ5EJcBIkkxcIRkCfssJyPH/9JR0YBoYCUgIgT9qeJc9xzYespLp93L7v1BpVs6pQyRkI7yvO/tMPyiqKhauRLdNZoUbn/0kf4RZQIDAQAB',
            'alipayRootCert'=>'',
            'loginAccount'=>'',
            'loginPassword'=>'',
            'ipWhite' => '',
        ],
    ],

    'shoufu' => [
        'name' => '易收付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => false,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\Shoufu",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cId' => '商户号',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://ni000001.com',
            'cId' => '190319FSRCXDGYA8',
            'ipWhite' => '104.18.51.180',
        ],
    ],
    'fnpay' => [
        'name' => '蜂鸟支付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => false,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\FnPay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cId' => '商户号',
            'apiKey' => '接口秘钥',
            'appPublicKey' => '接口公钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'http://api.aiiipay.cn',
            'cId' => '10011',
            'apiKey' => 'MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIFD0Nc4Mkczc2LrHlnpiK0BXBqvL1vYvHjqFIYma144boU8LrG397WlvKnHIfBsVVvwpwy2MkZ/gk1bkNPQlHGHoCvDO9vAI2r8utKz9BfxgzDh2Kvs1ZmaA8epJWojfr7iwllAq6etIzeqpv/BOb5oK2WAMHOm1+DlprW3DllDAgMBAAECgYBwyhuPrxkvx1UHGuCA06TOUEFthy5rldHeL2F5LEzDCbplxv13VG5vsQ3NllOm1OAmOPWJwfBcUyX/GcZlC7p5l4qH387Fn7/cUs3LqCkOek3mwBxXaNfdWetCfzXWZ6V3VdUlDQc0w5Z5eVrrtQYpL6zLis3tZSPbMEYr5+JRAQJBAL0sbvPc8e5yA4cRaQml0YUP8rDSTwwy0qSt1Aacid7qZCIuffvy6451hEgrL3GGF2iXtgyktLFjuJ6a5MoGGEUCQQCu7abYcBRx1GBbQdhN9KNh3YjoqpK4Bpl3X9o7R+JI5UyXQ4Mn30NOVS5fGPGeab1kVNEngXdjZdSGgLsWg1fnAkEAtxSDpNtWARCyvUtqPn4OUhrnI53GBuZA2kOpCWUCQYzSsAoSv32P32V4SmgRGGtPyFfbRk042tzJ1iXN+n7/iQJACQWQuVDufQBrB8nZkguv8Xgve3BwqLUObS2wX6ZRcVkCHjsJJKFLI1sZTSZIL9dcQTRupQ70TVgPIfC5tWuIuQJAfeNwuZn9BQeI7Z0a+k6mBElEIktH7AlFFHPgvD1byr/rhh0O0s406IUgkjJPALQ4kYinp/LauPmL+dURKYeRFw==',
            'appPublicKey' => 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCBQ9DXODJHM3Ni6x5Z6YitAVwary9b2Lx46hSGJmteOG6FPC6xt/e1pbypxyHwbFVb8KcMtjJGf4JNW5DT0JRxh6ArwzvbwCNq/LrSs/QX8YMw4dir7NWZmgPHqSVqI36+4sJZQKunrSM3qqb/wTm+aCtlgDBzptfg5aa1tw5ZQwIDAQAB',
            'ipWhite' => '',
        ],
    ],
    'yilian' => [
        'name' => '易联',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\Yilian",
        'paramDesc' => [
            'company' => '公司',
            'gateway' => '接口网关',
            'cId' => '商户号',
            'privateKey' => '接口私钥',
            'channelPK' => '通道公钥',
            'ipWhite' => '回调ip白名单',
            'settlementGateway' => '代付接口网关',
            'settlementMerchantNo' => '代付登录号',
            'settlementMerchantKey' => '代付商户秘钥',
            'settlementThirdPubKey' => '代付第三方公钥',
            'settlementRsaKeyPath' => '代付RSA私钥文件',
            'settlementRechargePrikey' => '代付充值密钥',
            'settlementRechargeMerchantNo' => '代付充值商户号',
            'settlementRechargePEBDnaMerchantNo' => '代付充值商户号（私卡）',
            'settlementRechargePEBDnaPrikey' => '代付充值密钥（私卡）',
            'settlementRechargeUrl' => '代付充值网关',
            'settlementSystemNo' => '代付系统商户编号',
            'settlementSystemKey' => '代付系统商户密钥',
        ],
        'param' => [
            'company' => '北京嘉亿',
            'gateway' => 'https://tmobile.payeco.com',
            'cId' => '502050004336',
            'privateKey' => 'MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAP719x49KqMmV/YUFEWaOff4UBiUrfmVHm5EAKbvGfmaIiQeFOPwnULqZs/8D3piUwaDzXUm0uf+5/DTyG7Wq5+MsC72DWUUdmgcRpeGpUtcTeq3/rF1CI1GhY9Ixj4qqDILQLZ4VaNtIJtJYgl7oIejzGYw7ftPx1WbT3HQUoNVAgMBAAECgYEAu/0b4l3zTCx/et+/OrrGt0GNvTITPQ1oTKEzYeK2YkX1mm/bs128dpRijkQqHXDWCt2v5gtkQs6+seFVzfPWweq4a0B96GaXJwkVtW2sTv7TQ0Av+smDx28/45KKj62NeUpC4wNlDj4g/6pKYc1RGjd0EjWsZaV2g2lFfXhhMhkCQQD/pWTNh+EE2TYubQK8R8vPRpIlM/8KZmyDARMyYiat0zRwsxrzkAd+0Od3GiyByPHO8L/ociheMVUV+hF9edsHAkEA/1BUI8ouXzB0WgF4i8Hd4J2tAICpEDUjASqOPET+FuK/9cJQVLMJdjmXLLlyiMWV+hQrDsxPytDbG+RcG3WrwwJAMJWXNbRYIFrDgEk5VtzyL99CkQ1zr99NSgxfQJkErs5PzgdL3PQHaKN9CdaQlM3CnsiEQEHJyDTp7bZLsqQA6wJADR/rA1/8XEZYZNwYf067AjX408LJbhzdLM0sPKrrSO/lIFQZ3xDJFrvFKrZpzeAiYpWw1PTp0SpFaTynA35cEwJBALVs0W74Q5c1/mM9v2OzpEJmMm6n73NHuaCahg2dUF24TIQVGGwxJ3r0mW2PlvBLHAt3u/eP/rwNM6c9uwEsBM0=',
            'channelPK' => 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCoymAVb04bvtIrJxczCT/DYYltVlRjBXEBFDYQpjCgSorM/4vnvVXGRb7cIaWpI5SYR6YKrWjvKTJTzD5merQM8hlbKDucxm0DwEj4JbAJvkmDRTUs/MZuYjBrw8wP7Lnr6D6uThqybENRsaJO4G8tv0WMQZ9WLUOknNv0xOzqFQIDAQAB',
            'ipWhite' => '',
            'settlementGateway' => 'https://agent.payeco.com/service',
            'settlementMerchantNo' => '18358005165',
            'settlementMerchantKey' => '91120291',
            'settlementThirdPubKey' => 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDc+L2JGUKlGtsFm2f/wuF2T6/8mc6yrN8tLPgsx7sxAatvMvunHLXKC8xjkChHqVfJgohV4OIWe8zCw7jPsJMiPvrNnFHJ2Mumg/zQ8eZOnzMA0LDqBNFvZnOpy2XtagQn4yxxzG9+9h4P5eNojC3vD2t3H/6q5V3Cd022/egIZQIDAQAB',
            'settlementRsaKeyPath' => 'yilian-yijia.pfx',

            'settlementRechargeUrl'=>'https://testebank.payeco.com:8143/ebank/servlet/DnaPayB2C',
            'settlementRechargePrikey'=>'123456',
            'settlementRechargeMerchantNo'=>'302020000114',
            'settlementRechargePEBDnaMerchantNo'=>'302020000114',
            'settlementRechargePEBDnaPrikey'=>'123456',
            'settlementSystemNo'=>'902020000819',
            'settlementSystemKey'=>'0A37D991ED574EE3',

        ],
        'config' => [
            'insideRecharge' => [
                'open'=> 0,
                'rechargeMin'=> 10,
                'rechargeMax'=> 200000,
                'shangyouPercent'=> 0.0033,
                'shangyouFixed'=> 0,
                'xiayouPercent'=> 0.008,
                'xiayouFixed' => 15
            ],
            'outsideRecharge' => [
                'open' => 0,
                'rechargeMin'=>10,
                'rechargeMax'=>200000,
                'shangyouPercent'=> 0.003,
                'shangyouFixed'=> 15,
                'xiayouPercent'=> 0.005,
                'xiayouFixed' => 15
            ],
        ]

    ],


    'dblpay' => [
        'name' => '大菠萝支付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => false,
        'path' => "\App\Channels\Lib\DblPay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cId' => '商户号',
            'apiKey' => '接口秘钥',
            'appPublicKey' => '接口公钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://pay.tasttast.com/Pay_Index.html',
            'cId' => '180778794',
            'apiKey' => 'bh4vz4ulwrv2hewdwknnppp9zkc17alo',
            'appPublicKey' => 'bh4vz4ulwrv2hewdwknnppp9zkc17alo',
            'ipWhite' => '',
        ],
    ],

    'hipay' => [
        'name' => 'HiPay支付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => false,
        'path' => "\App\Channels\Lib\HiPay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cId' => '商户号',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://www.hipay8888.com',
            'cId' => '',
            'ipWhite' => '',
        ],
    ],

    'rxpay' => [
        'name' => '任性付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => false,
        'path' => "\App\Channels\Lib\RXPay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cId' => '商户号',
            'apiKey' => '接口秘钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'http://www.renxingpay.cn',
            'cId' => '190499413',
            'apiKey' => 'sr17a4ue72u8s2lunuvpb40lpvbgai5z',
            'ipWhite' => '',
        ],
    ],
    'yhpay' => [
        'name' => '亚汇支付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => false,
        'path' => "\App\Channels\Lib\YHPay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cId' => '商户号',
            'apiKey' => '接口秘钥',
            'appPublicKey' => '接口公钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'http://api.bq916.vip',
            'cId' => '10145',
            'apiKey' => 'z4xdwerzv8ndeeauuljkhuf6b972ixoq',
            'appPublicKey' => 'z4xdwerzv8ndeeauuljkhuf6b972ixoq',
            'ipWhite' => '',
        ],
    ],
    'dcpay' => [
        'name' => 'DCPay支付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => true,
        'settlementType' => ['alipay' => '支付宝代付','bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\DCPay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cId' => '商户号',
            'apiKey' => '接口秘钥',
            'appPublicKey' => '接口公钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'http://34.85.59.143:8080/gateway/transaction/request',
            'cId' => 'U2019091110001266',
            'apiKey' => 'd8a21f3cdfae4d3fa3e6a9fc5ebad679',
            'appPublicKey' => '2c0f6a84f81a4bcd890b556850ab2444',
            'ipWhite' => '',
        ],
    ],
    'yindupay' => [
        'name' => '印度支付',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\YinduPay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'cId' => '商户号',
            'apiKey' => '接口秘钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://stg.mpursewallet.com/api/v2/gateway',
            'cId' => 'Mct_test_10001_PartnerId',
            'apiKey' => 'A3E8A4C522C8609F1166CCEB8728B9685EEDD70976F5FC8F48F570E777095963',
            'ipWhite' => '',
        ],
    ],
    'dqpay' => [
        'name' => '多钱代付',
        'open' => true,
        'openQuery' => true,
        'openPay' => false,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\Dqpay",
        'paramDesc' => [
            'cId'=>'商户号',
            'gateway' => '接口网关',
            'apiKey' => '接口秘钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'cId'=>'dadong',
            'gateway' => 'https://gateway.tradeky.net',
            'apiKey' => 'tzGNd5lU9RgWnT7D91DAqkW3C548qTcQ',
            'ipWhite' => '',
        ],
    ],

    'psql' => [
        'name' => '敏付(磐石千里)',
        'open' => true,
        'openQuery' => true,
        'openPay' => false,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\Psql",
        'paramDesc' => [
            'gateway' => '接口网关',
            'appAccount' => '商户号',
            'nodeId' => '节点号',
            'aesKey' => 'aes加密密钥',
            'rsaPrivateKey' => '商户rsa私钥',
            'rsaPublicKey' => '平台rsa公钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://mrch.gdpanshi.com/psqltpPay',
            'appAccount' => '1008300000000278',
            'nodeId' => '10080279',
            'aesKey' => 'Ut9c3XdF0y8G+Hw6I0he2w==',
            'rsaPrivateKey' => 'MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC6f/G9wvbTbg2uku77eAcc53k3xVzzlHQWr7zsNH0nRE2IOVkVQQ9yoE6x8SO7yWWHUBbF2rQe/3saXY5YM3pRUsDLPu9jAHvwhqnLAhF2WFPbw/LmWkVAVATyfYbkLHhPDu+Xkq3j61YMxH5Xf+tfDRmHpjtaLcTvDWPidDQNbldkXXAJ9b1QAo+jHYUIMW4LChMcUqxhGlgtjnrQe+YbLhbkd8nMTM0Dv6fl+Nhrt/ufojWQzXPXSoruuCyS5C75fygnASs225Pov33CsCYIVFxwvxeo2UBdEno8d43ymQ+W1ol24ewpMQ322TDUbt5HFkVRz3cWcNMoq0gUlT/JAgMBAAECggEBAJsmBP1QS/XoAAnSwm0AlSo+hmEXFxSr00dsO0ZlBBi+gaFp0+oSjb9WDSGK8acvC/9daRR/tIh1EPwGCHznlkJBDZIHcS5zIKgf3vC7b7t8D4cro85uGl5BhzwToTwAorViP39gzrhk9tj4PgKcsDoKs8pdR9LlcIdOJGInOYZRbgKKYdOF6PR9bvN6MbIauJR1j8SQf0rGkrx/QDIyR3avgu5/hfWU6aYpi4G4vKnz8hYYAlVNV7Zl6JNdeV+H7WryWv7mQnRejZ3UAP5Z6pnJX3u2/57nh0ruOTg5RkcN0r0ixclI9Xd9zX1SufF6swV3MP+cSKTkF5nxfNona2ECgYEA+m4aK8wqN86qS/H322MswuLmrO/EEmIFOeKgPMS7lrUJpU0NeUZahFPn6Qfsagj/zkvBhhvIQQT9HL5QhbD6+XFPRLQIZJ09VCNxeHMytvjt5ZkQ2KvCQm4J2RPHQ3tqAvG20QKm2IsgUEylDAgG6692tDzcWBmtHxxCChUOBU8CgYEAvqXWAma0IrM8047+8n+720fGq7ujSAQWq46mSO7HEFybGfaqpB3+KGehHpDL8OiYapXUoBGDp1P8OLESSKXglWt9NItYVS5xWb6cWP4TH2gbtJyZa3l4B1nNhYTcBcvyaZCgI4fOv1I+2KipnEU6b64mxHmsDGM3pJTNNMcf02cCgYEAhP82LO5nuW2rKVwe6sdXvURth4hqU+z0o5JE0SEWEuqgbcZnEnIXnlFFR4/qsUGIQRIge82DY2x30+0KrIWaNCFGHNGT54NOT8HnADYFyACZrybEOJ23NDpmRn/ngmInodqm4YeL/lKc3ahmuuYEbuSnoP71cmBofa4vMFWQNacCgYEAgXxhPoBDGM5kIcydnFblYKn/ZeSrod4lB6B7kE2dJp+/OIMwowc7+HVqGTh/S8CuxLW/FHjQ0nVYeajKok0HnHTFNUrvU+uXUT0FM+xdUJeFOcai7TwzKcr0rBrw1X8PxmNUYM18vrU9uinUCS974R6HdiqtkDxTLpViStZz50ECgYBpyuyPGkP66jItV0k+XUXOX8wwltM3Cb2OCCOYraJpZFhLOcIMSBc0bu1nERyB7YT6pHMbt7D/TvY7/61MifGGWuZvzcgJq/frgNF/NI6AizyLRD+qX0rn64RTBnSdY+xmT0G6gqnlqvaIIz0nTRIgldoB6id1We8e2VsRUtYivg==',
            'rsaPublicKey' => 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArnScyrNiZ8TdynY8SmUEB6+u59BmKl2mbVJkXT80kv2ErP22HM9u0PXfXLzNeVz/fbJd2vZ04PCgFbWc+ajm7jrMIg9e5TDjtJMIrHbaIDjVthpi75uV8Q/2546XUxCj68jB9oN3r0T1Is0hM06w8KFSwEBfA2C3e/3wmr2Jw/1cqSO6V45RSOtNShrTigUQwJAwrUS/It5BR2gsYgbgczIysg0UDYwVGpNINAome4MPbkZTeEnkRwXyHYfc+CRC1Lf0z3wS8qCSJ+8xVAEi2xYSBuzWuEkj5Bj1TxqdR5BB+5a4aY//7GZUnLobyjX1Ad8pAEK1J4AB3vXUdApIIQIDAQAB',
            'ipWhite' => '',
        ],
    ],

    'loropay' => [
        'name' => 'loropay',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\LoroPay",
        'paramDesc' => [
            'gateway' => '接口网关',
            'description' => '渠道备注',
            'merchantNo' => '商户号',
            'platformPublicKey' => '第三方平台公钥',
            'merchantPrivateKey' => '商户私钥',
            'merchantPublicKey' => '商户公钥',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'gateway' => 'https://api.payloro.tech',
            'description' => 'loropay',
            'merchantNo' => 'NO120910918674',
            'platformPublicKey' => 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCI12CiMSGgXhBVk1yXom9akvn8CPXdEpmnsJv2N8kvCwLSLsfxej2uyzyatyoH3VtztOYGJxkm3MYBv8od+fLyZlZhWrar13o8BEz8q5GTgwlzadPoSs8vnJGNqMX7hYTSg6vaQJOQ97enOIMEoSYH/TaNj7D0r64I+G7Fz01rDQIDAQAB',
            'merchantPrivateKey' => 'MIICXAIBAAKBgQCLJtfTZ/fH1SfnXjc24/axLB2wPEZXtHKdInZpOeRfLp/fvFbvm0cd3Say1T5xrmXHFx2qofRx8rpVmXcYrr6hw+aCG7jV7hC41uQXeNpvh+hcRTAQObhyceRQw3PEaLZp2jPs7+Xbvu8h83gG5smEHnlb2jqEdV5u/N5p2ZbzbQIDAQABAoGAUegbQiUAhG/DfTzH41dr7f25u/K+tQFSNYwDhwy8kAoxsNB7m64avklebgV3LBMrdXT10WpjKG9nntsmbzDspAxEbbglNOhQxKbHJmXdz9eSCJGEM7jpq1ejUc4KuUL4kPT6FZdcv+ttontgihrGjezJq3f9BjvQTPqgK3tzm0ECQQDOe0k6j/WV2Uxcx5ooy4+/6QA//xSjlyr89rjUwdN52r+2Fy6mCkBs/BGxmb/aCqFPTPA+YfpuqL0o1MsfhSyvAkEArIXpzFQ3pBj4X0aONxPu0rWQPL6yxB+NUIRpoP6N/RL1VTNKHjPLQltzy1nw3Nqlu8xg+tIS8JS4cfI4SsyAowJAZdmMYpW2NydLsoxGr47RpoFBPVAOly8u5j6xJ0lAjl/npuNCgGaYJuojtC4540zRCvPRoYPk6wbS37wvQaoIQwJABhdsW+SVWlvvWR3ao6M2iYYTo7FwCnC6wp8KQ775MHhc5Tc8ZLibcqpb+lAgqwulUm4y9mg4dvopUQymZC24VQJBAJk+b6FVR3SI/YnDR0Me5FYgGC333Xus3rhohw16TCtDzEdSRrLWcS6AGGYssU7K8ihp59TzH2PGHNVDuacIUR4=',
            'merchantPublicKey' => 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCLJtfTZ/fH1SfnXjc24/axLB2wPEZXtHKdInZpOeRfLp/fvFbvm0cd3Say1T5xrmXHFx2qofRx8rpVmXcYrr6hw+aCG7jV7hC41uQXeNpvh+hcRTAQObhyceRQw3PEaLZp2jPs7+Xbvu8h83gG5smEHnlb2jqEdV5u/N5p2ZbzbQIDAQAB',
            'ipWhite' => '',
        ],
    ],

    'TianciPay' => [
        'name' => 'TianciPay',
        'open' => true,
        'openQuery' => true,
        'openPay' => true,
        'openSettlement' => true,
        'settlementType' => ['bank' => '银行卡代付'],
        'path' => "\App\Channels\Lib\TianciPay",
        'paramDesc' => [
            'company' => '上游账号',
            'gateway' => '接口网关',
            'description' => '渠道备注',
            'merchantNo' => '商户号',
            'api_token' => 'api_token',
            'notify_token' => 'callback_token',
            'ipWhite' => '回调ip白名单',
        ],
        'param' => [
            'company' => 'LD99',
            'gateway' => 'https://tiancip030905.com',
            'description' => 'Tianci',
            'merchantNo' => 'LD99',
            'api_token' => 'F8Q6MKxWb4B0QnR2i6Wuge37oNgmhkdNexI9vWduFzauO3ZIHBk28xO1qUrZ',
            'notify_token' => 'ARSHBruc4u1LoQSiqI2CCSbsuSBACgu7xdhLDD2AjtjOlPv7efg8FxvgSf9d',
            'ipWhite' => '',
        ],
    ],
];
