<?php
return [
    'EBank' => '网银',
    'Quick' => '快捷支付',
    'OfflineWechatQR' => '线下微信扫码',
    'OfflineAlipayQR' => '线下支付宝扫码',
    'OnlineWechatPB' => '微信公众号',
    'OnlineWechatQR' => '线上微信扫码',
    'OnlineAlipayQR' => '线上支付宝扫码',
    'OnlineWechatH5' => '线上微信H5',
    'OnlineAlipayH5' => '线上支付宝H5',
    'OnlineAlipayOriginalH5' => '线上支付宝原生H5',
    'OnlineWechatOriginalH5' => '线上微信原生H5',
    'QQPayQR' => 'QQ扫码',
    'QQPhonePay' => 'QQ手机',
    'UnionPayQR' => '银联扫码',
    'UnionPay' => '银联快捷/云闪付',
    'JDPayQR' => '京东扫码',
    'MeiTuanQR' => '美团扫码',
    'DianPingQR' => '大众点评扫码',
    'BestPayQR' => '翼支付',
    'ApplePay' => 'ApplePay',
    'EBankQR' => '银行付款码',
    'BaiduWallet' => '百度钱包',
    // 'EntrustSettlement' => '委托代付',
    // 'AdvanceSettlement' => '垫资结算',
    // 'HolidaySettlement' => '节假日结算',
    'D0Settlement' => 'D0结算',
    'EnterpriseEBank' => '企业网银',
    'PersonalEBank' => '个人网银',
    'PersonalEBankDNA' => '个人网银DNA',
    'EnterpriseAlipay' => '企业支付宝',
    'AlipayEBank' => '支付宝网银',

    'gcash' => 'gcash',
    'grabpay' => 'grabpay',
    '711_direct' => '711_direct',
    'da5' => 'da5',
    'qr' => 'qr',
    'payngo' => 'payngo',
    'posible' => 'posible',
    'RLNT' => 'RLNT',
    'RDS' => 'RDS',
    'UBPB' => 'UBPB',
    'RCBC' => 'RCBC',
    'SMR' => 'SMR',
    'LBC' => 'LBC',
    'ussc' => 'ussc',
    'PLWN' => 'PLWN',
    'partnerpay' => 'partnerpay',
    'RDP' => 'RDP',
    'BPIA' => 'BPIA',
    'ECPY' => 'ECPY',
    'CEBL' => 'CEBL',

];
